### ISSUE TITLE
Can you please describe how someone else can set this exact setup up?

### ISSUE THREAD

**Issue by nikitavoloboev** [yoshuawuyts/knowledge#49]
I wish to do something similar (or nearly exact) as I quite like the way you can search through the knowledge base and the layout.

However I am struggling in setting it up. I set up a GitBook account and made the wiki page but it fails to render like yours does.

Thank you for any help.

**Comment by nikitavoloboev** [comment]
I just get this : 

![2017-09-21 at 21 24](https://user-images.githubusercontent.com/6391776/30714511-576774cc-9f13-11e7-8bd9-0949f3cbe14c.png)

And it doesn't actually give me anything to search over. 😞

**Comment by yoshuawuyts** [comment]
Oh yeah just read the markdown haha - gitbook was a failed experiment I
never turned off lol

**Comment by nikitavoloboev** [comment]
I see. Can you still please share how to set it up like yours? 💛

I can make the markdowns but how do I make the search over them and all the nice things you have.

**Comment by nikitavoloboev** [comment]
I wold be forever grateful for that. 💚

**Comment by yoshuawuyts** [comment]
Haha, well I just use lots of markdown files and that's about it haha

**Comment by nikitavoloboev** [comment]
Yeah, but how do you render them like that afterwards?

**Comment by yoshuawuyts** [comment]
Hah, yeah so I don't! ✨ Terminal only :D

**Comment by nikitavoloboev** [comment]
Yeah I love the terminal too.

But that doesn't say how you render them like that. Or it's a secret? 😞

**Comment by nikitavoloboev** [comment]
Or is it something that Git Books provides? I can't find a way to replicate that there.

**Comment by nikitavoloboev** [comment]
Oh nvm. I figured it out. Git Books does it all then. 🎊
