### ISSUE TITLE
Error in wasm notes

### ISSUE THREAD

**Issue by bnoordhuis** [yoshuawuyts/knowledge#52]
https://github.com/yoshuawuyts/knowledge/blob/master/computers/2018-05-31-wasm-notes.md says this:

> Libuv is not ABI stable - that's probably a thing to look at stabilizing.

I don't know if that's a direct quote or a transcription error but it's wrong: libuv _is_ ABI-stable.

**Comment by yoshuawuyts** [comment]
@bnoordhuis thanks for sharing! It was a direct transcription from what was said in the meeting. I'll add a comment with your clarification.

**Comment by yoshuawuyts** [comment]
Done! Thanks again :grin:
